services:
  # cloudtrip.homework.web:
  #   container_name: cloudtrip-homework-web
  #   build:
  #     context: .
  #     dockerfile: cloudtrip.homework.client/Dockerfile
  #   ports:
  #     - "9090:80"
  #   depends_on:
  #     - cloudtrip.homework.server

  cloudtrip.homework.server:
    container_name: cloudtrip-homework-server
    image: ${DOCKER_REGISTRY-}cloudtriphomeworkserver
    build:
      context: .
      dockerfile: CloudTrip.Homework.Server/Dockerfile

  mongo:
    container_name: mongo-db
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - cloudtrip_homework:/data/db

  redis:
    image: redis:7.2.4
    container_name: cloudtrip-homework-redis
    ports:
      - "6679:6379"
 
volumes:
  cloudtrip_homework: